# Generated by Django 5.0.1 on 2024-02-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
